name: Handoff AI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo pip3 install robotframework==7.0.1 \
          && sudo pip3 install robotframework-pabot \
          && sudo pip3 install allure-robotframework==2.9.44 \
          && sudo pip3 install robotframework-seleniumlibrary==6.0.0 \
          && sudo pip3 install robotframework-appiumlibrary==2.1.0 \
          && sudo pip3 install robotframework-faker==5.0.0 \
          && sudo pip3 install robotframework-requests==0.9.2 \
          && sudo pip3 install --upgrade requests \
          && sudo pip3 install Appium-Python-Client==1.3.0
                
      - name: Check dependencies
        run: |
          sudo pip3 list robotframework

      - name: Set up Java (required for Allure CLI)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
  
      - name: Install allure
        if: always()
        run: |
          curl -o allure-2.13.8.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz \
          && sudo tar -zxvf allure-2.13.8.tgz -C /opt/ \
          && sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure \
          && allure --version

      - name: Run robot
        id: robot
        continue-on-error: true
        run: |
          pabot --ordering .pabotsuitenames --processes 2 --listener allure_robotframework:allure-results --output output.xml -v run_number:$GITHUB_RUN_ID ./${{ github.event.inputs.path }}/tests/
          
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
